import { ILabelValue } from '../questions/Questions.types.ts';

export const questionListMock: ILabelValue[] = [
  {
    label: 'Flagstaff',
    value: 'Flagstaff',
  },
  {
    label: 'Mesa',
    value: 'Mesa',
  },
  {
    label: 'Phoenix',
    value: 'Phoenix',
  },
  {
    label: 'Tuscon',
    value: 'Tuscon',
  },
];

export const usStates = [
  {
    name: 'Alabama',
    capital: 'Montgomery',
    cities: [
      {
        name: 'Birmingham',
        location: { latitude: 33.5207, longitude: -86.8024 },
        population: 209880,
      },
      {
        name: 'Huntsville',
        location: { latitude: 34.7304, longitude: -86.5861 },
        population: 205764,
      },
      {
        name: 'Mobile',
        location: { latitude: 30.6954, longitude: -88.0399 },
        population: 189572,
      },
      {
        name: 'Montgomery',
        location: { latitude: 32.3801, longitude: -86.3004 },
        population: 198218,
      },
      {
        name: 'Tuscaloosa',
        location: { latitude: 33.2098, longitude: -87.5692 },
        population: 101764,
      },
    ],
    location: { latitude: 32.8067, longitude: -86.7911 },
    population: 4908621,
  },
  {
    name: 'Alabama',
    capital: 'Montgomery',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Alaska',
    capital: 'Juneau',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Arizona',
    capital: 'Phoenix',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Arkansas',
    capital: 'Little Rock',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'California',
    capital: 'Sacramento',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Colorado',
    capital: 'Denver',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Connecticut',
    capital: 'Hartford',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Delaware',
    capital: 'Dover',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Florida',
    capital: 'Tallahassee',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Georgia',
    capital: 'Atlanta',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Hawaii',
    capital: 'Honolulu',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Idaho',
    capital: 'Boise',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Illinois',
    capital: 'Springfield',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Indiana',
    capital: 'Indianapolis',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Iowa',
    capital: 'Des Moines',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Kansas',
    capital: 'Topeka',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Kentucky',
    capital: 'Frankfort',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Louisiana',
    capital: 'Baton Rouge',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Maine',
    capital: 'Augusta',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Maryland',
    capital: 'Annapolis',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Massachusetts',
    capital: 'Boston',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Michigan',
    capital: 'Lansing',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Minnesota',
    capital: 'St. Paul',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Mississippi',
    capital: 'Jackson',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Missouri',
    capital: 'Jefferson City',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Montana',
    capital: 'Helena',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Nebraska',
    capital: 'Lincoln',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Nevada',
    capital: 'Carson City',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'New Hampshire',
    capital: 'Concord',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'New Jersey',
    capital: 'Trenton',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'New Mexico',
    capital: 'Santa Fe',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'New York',
    capital: 'Albany',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'North Carolina',
    capital: 'Raleigh',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'North Dakota',
    capital: 'Bismarck',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Ohio',
    capital: 'Columbus',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Oklahoma',
    capital: 'Oklahoma City',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Oregon',
    capital: 'Salem',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Pennsylvania',
    capital: 'Harrisburg',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Rhode Island',
    capital: 'Providence',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'South Carolina',
    capital: 'Columbia',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'South Dakota',
    capital: 'Pierre',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Tennessee',
    capital: 'Nashville',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Texas',
    capital: 'Austin',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Utah',
    capital: 'Salt Lake City',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Vermont',
    capital: 'Montpelier',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Virginia',
    capital: 'Richmond',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Washington',
    capital: 'Olympia',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'West Virginia',
    capital: 'Charleston',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Wisconsin',
    capital: 'Madison',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
  {
    name: 'Wyoming',
    capital: 'Cheyenne',
    cities: [],
    location: { latitude: -1, longitude: -1 },
    population: -1,
  },
];
